#!/bin/sh

# jp - front end for JabberPoint slideshow program
# $Id$

JPHOME=/home/ian/workspace/jabberpoint/build
CLASSPATH=$CLASSPATH:${JPHOME}

case $* in
	0)	echo "Usage: jp file" >&2;;
	*)	java -DJABBERPOINTHOME=${JPHOME} jp.JabberPoint $*
esac
